services:
  - type: web
    name: crm-api
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/healthcheck
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: COOKIE_SECURE
        value: "true"
